export const BASE_URL = 'https://demo.nhanhtravel.com/';
export const BASE_URL_API = 'https://demo.nhanhtravel.com/api/';
// export const BASE_URL = 'https://vigomanager.com/';
// export const BASE_URL_API = 'https://vigomanager.com/api/';
// export const BASE_URL = 'http://localhost/vigolf_web/';
// export const BASE_URL_API = 'http://localhost/vigolf_web/api/';
export const REST_KEY = "api_key";

export const GET_TOKEN = () => {
  return localStorage.getItem("token");
};
export const GET_LANG_CODE = () => {
  return localStorage.getItem("lang") ? localStorage.getItem("lang") : JSON.stringify('vi');
};

export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_ERROR = "FETCH_USER_INFO_ERROR";

export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_CATEGORY_LIST_SUCCESS = "FETCH_CATEGORY_LIST_SUCCESS";
export const FETCH_CATEGORY_LIST_ERROR = "FETCH_CATEGORY_LIST_ERROR";

export const FETCH_BRAND_LIST = "FETCH_BRAND_LIST";
export const FETCH_BRAND_LIST_SUCCESS = "FETCH_BRAND_LIST_SUCCESS";
export const FETCH_BRAND_LIST_ERROR = "FETCH_BRAND_LIST_ERROR";

export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";
export const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS";
export const FETCH_PRODUCT_LIST_ERROR = "FETCH_PRODUCT_LIST_ERROR";


export const TOUR_LIST = "TOUR_LIST";
export const TOUR_LIST_SUCCESS = "TOUR_LIST_SUCCESS";
export const TOUR_LIST_ERROR = "TOUR_LIST_ERROR";

export const TOUR_DETAIL = "TOUR_DETAIL";
export const TOUR_DETAIL_SUCCESS = "TOUR_DETAIL_SUCCESS";
export const TOUR_DETAIL_ERROR = "TOUR_DETAIL_ERROR";

export const GOLF_LIST = "GOLF_LIST";
export const GOLF_LIST_SUCCESS = "GOLF_LIST_SUCCESS";
export const GOLF_LIST_ERROR = "GOLF_LIST_ERROR";

export const GOLF_DETAIL = "GOLF_DETAIL";
export const GOLF_DETAIL_SUCCESS = "GOLF_DETAIL_SUCCESS";
export const GOLF_DETAIL_ERROR = "GOLF_DETAIL_ERROR";

export const GOLF_PRICE = "GOLF_PRICE";
export const GOLF_PRICE_SUCCESS = "GOLF_PRICE_SUCCESS";
export const GOLF_PRICE_ERROR = "GOLF_PRICE_ERROR";

export const GOLF_SCORECARD = "GOLF_SCORECARD";
export const GOLF_SCORECARD_SUCCESS = "GOLF_SCORECARD_SUCCESS";
export const GOLF_SCORECARD_ERROR = "GOLF_SCORECARD_ERROR";


export const ADD_CART_LIST = "ADD_CART_LIST";
export const ADD_CART_LIST_SUCCESS = "ADD_CART_LIST_SUCCESS";
export const ADD_CART_LIST_ERROR = "ADD_CART_LIST_ERROR";

export const ADD_CART_DETAIL = "ADD_CART_DETAIL";
export const ADD_CART_DETAIL_SUCCESS = "ADD_CART_DETAIL_SUCCESS";
export const ADD_CART_DETAIL_ERROR = "ADD_CART_DETAIL_ERROR";

export const COUNTRY_USER = "COUNTRY_USER";
export const COUNTRY_USER_SUCCESS = "COUNTRY_USER_SUCCESS";
export const COUNTRY_USER_ERROR = "COUNTRY_USER_ERROR";


export const SLIDE_IMAGE_LIST = "SLIDE_IMAGE_LIST";
export const SLIDE_IMAGE_LIST_SUCCESS = "SLIDE_IMAGE_LIST_SUCCESS";
export const SLIDE_IMAGE_LIST_ERROR = "SLIDE_IMAGE_LIST_ERROR";


export const NEW_LIST = "NEW_LIST";
export const NEW_LIST_SUCCESS = "NEW_LIST_SUCCESS";
export const NEW_LIST_ERROR = "NEW_LIST_ERROR";

export const ALL_NEW_LIST = "ALL_NEW_LIST";
export const ALL_NEW_LIST_SUCCESS = "ALL_NEW_LIST_SUCCESS";
export const ALL_NEW_LIST_ERROR = "ALL_NEW_LIST_ERROR";


export const NEW_DETAIL = "NEW_DETAIL";
export const NEW_DETAIL_SUCCESS = "NEW_DETAIL_SUCCESS";
export const NEW_DETAIL_ERROR = "NEW_DETAIL_ERROR";

export const GOLF_PACKAGE_LIST = "GOLF_PACKAGE_LIST";
export const GOLF_PACKAGE_LIST_SUCCESS = "GOLF_PACKAGE_LIST_SUCCESS";
export const GOLF_PACKAGE_LIST_ERROR = "GOLF_PACKAGE_LIST_ERROR";

export const GOLF_PACKAGE_DETAIL = "GOLF_PACKAGE_DETAIL";
export const GOLF_PACKAGE_DETAIL_SUCCESS = "GOLF_PACKAGE_DETAIL_SUCCESS";
export const GOLF_PACKAGE_DETAIL_ERROR = "GOLF_PACKAGE_DETAIL_ERROR";

export const GOLF_PACKAGE_PRICE = "GOLF_PACKAGE_PRICE";
export const GOLF_PACKAGE_PRICE_SUCCESS = "GOLF_PACKAGE_PRICE_SUCCESS";
export const GOLF_PACKAGE_PRICE_ERROR = "GOLF_PACKAGE_PRICE_ERROR";

export const HOTEL_LIST = "HOTEL_LIST";
export const HOTEL_LIST_SUCCESS = "HOTEL_LIST_SUCCESS";
export const HOTEL_LIST_ERROR = "HOTEL_LIST_ERROR";

export const HOTEL_DETAIL = "HOTEL_DETAIL";
export const HOTEL_DETAIL_SUCCESS = "HOTEL_DETAIL_SUCCESS";
export const HOTEL_DETAIL_ERROR = "HOTEL_DETAIL_ERROR";

export const HOTEL_PRICE = "HOTEL_PRICE";
export const HOTEL_PRICE_SUCCESS = "HOTEL_PRICE_SUCCESS";
export const HOTEL_PRICE_ERROR = "HOTEL_PRICE_ERROR";

export const LANGUAGE_LIST = "LANGUAGE_LIST";
export const LANGUAGE_LIST_SUCCESS = "LANGUAGE_LIST_SUCCESS";
export const LANGUAGE_LIST_ERROR = "LANGUAGE_LIST_ERROR";


export const LANGUAGE_DETAIL = "LANGUAGE_DETAIL";
export const LANGUAGE_DETAIL_SUCCESS = "LANGUAGE_DETAIL_SUCCESS";
export const LANGUAGE_DETAIL_ERROR = "LANGUAGE_DETAIL_ERROR";

export const CITY_LIST = "CITY_LIST";
export const CITY_LIST_SUCCESS = "CITY_LIST_SUCCESS";
export const CITY_LIST_ERROR = "CITY_LIST_ERROR";

export const ORDER_VIEW_DETAIL = "ORDER_VIEW_DETAIL";
export const ORDER_VIEW_DETAIL_SUCCESS = "ORDER_VIEW_DETAIL_SUCCESS";
export const ORDER_VIEW_DETAIL_ERROR = "ORDER_VIEW_DETAIL_ERROR";

export const SETUP_ADDRESS = "SETUP_ADDRESS";
export const SETUP_ADDRESS_SUCCESS = "SETUP_ADDRESS_SUCCESS";
export const SETUP_ADDRESS_ERROR = "SETUP_ADDRESS_ERROR";

export const SETUP_ADDRESS_DETAIL = "SETUP_ADDRESS_DETAIL";
export const SETUP_ADDRESS_DETAIL_SUCCESS = "SETUP_ADDRESS_DETAIL_SUCCESS";
export const SETUP_ADDRESS_DETAIL_ERROR = "SETUP_ADDRESS_DETAIL_ERROR";

export const ORDER_HISTORY = "ORDER_HISTORY";
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS";
export const ORDER_HISTORY_ERROR = "ORDER_HISTORY_ERROR";
